CREATE DATABASE todo;
USE todo;

CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL CURRENT_TIMESTAMP,
    updated_at DATETIME CURRENT_TIMESTAMP,
);

CREATE TABLE post (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title TEXT NOT NULL,
    description VARCHAR(255), 
    created_at DATETIME NOT NULL CURRENT_TIMESTAMP, 
    updated_at DATETIME CURRENT_TIMESTAMP,

    FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE
);
